package pipeline

import (
	"time"
)

// ═══════════════════════════════════════════════════════
// EVENTS — the pipeline communicates via events
// ═══════════════════════════════════════════════════════

// EventType classifies pipeline events.
type EventType string

const (
	EventGUNew          EventType = "gu_new"           // New GU publication matching a bonus
	EventGUAbrogazione  EventType = "gu_abrogazione"   // GU signals abrogation/expiry
	EventGUProroga      EventType = "gu_proroga"       // GU signals extension
	EventGUModifica     EventType = "gu_modifica"      // GU signals modification
	EventRSSConferma    EventType = "rss_conferma"     // RSS quorum reached: confirmed
	EventRSSScadenza    EventType = "rss_scadenza"     // RSS quorum reached: expired
	EventRSSModifica    EventType = "rss_modifica"     // RSS quorum reached: amount changed
	EventRSSWeak        EventType = "rss_weak"         // RSS signal below quorum
	EventLinkOK         EventType = "link_ok"          // Link verified OK
	EventLinkBroken     EventType = "link_broken"      // Link broken (4xx/5xx/timeout)
	EventLinkRedirect   EventType = "link_redirect"    // Link permanently redirected
	EventLinkArchived   EventType = "link_archived"    // Page moved to archive section
)

// PipelineEvent is an event generated by any pipeline level.
type PipelineEvent struct {
	Type      EventType         `json:"type"`
	BonusID   string            `json:"bonus_id"`
	Source    string            `json:"source"`     // "L1:GU", "L3:RSS:FiscoOggi", "L4:LinkCheck"
	Level     int               `json:"level"`      // 1-5
	Timestamp time.Time         `json:"timestamp"`
	Data      map[string]string `json:"data,omitempty"`
	Trust     float64           `json:"trust"`      // 0.0-1.0
}

// ═══════════════════════════════════════════════════════
// RSS — feed definitions and article data
// ═══════════════════════════════════════════════════════

// RSSFeed defines a monitored RSS feed with trust score.
type RSSFeed struct {
	Name  string  `json:"name"`
	URL   string  `json:"url"`
	Trust float64 `json:"trust"` // 0.0-1.0, institutional=1.0, editorial=0.5-0.85
}

// Article is a parsed RSS article with extracted signals.
type Article struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Link        string    `json:"link"`
	PubDate     time.Time `json:"pub_date"`
	Source      string    `json:"source"`
	Trust       float64   `json:"trust"`
}

// SignalType classifies what an RSS article says about a bonus.
type SignalType string

const (
	SignalConferma          SignalType = "conferma"
	SignalScadenza          SignalType = "scadenza"
	SignalModificaImporto   SignalType = "modifica_importo"
	SignalModificaRequisiti SignalType = "modifica_requisiti"
)

// Signal is an extracted signal from an RSS article.
type Signal struct {
	Type    SignalType `json:"type"`
	BonusID string    `json:"bonus_id"`
	Source  string    `json:"source"`
	Trust   float64   `json:"trust"`
	Article Article   `json:"article"`
}

// CorroborationResult is the quorum calculation result for a bonus.
type CorroborationResult struct {
	BonusID           string      `json:"bonus_id"`
	Signal            SignalType  `json:"signal"`
	CumulativeTrust   float64     `json:"cumulative_trust"`
	IndependentSources int        `json:"independent_sources"`
	QuorumReached     bool        `json:"quorum_reached"`
	Action            ActionType  `json:"action"`
	Sources           []string    `json:"sources"`
	Confidence        float64     `json:"confidence"`
	TriggerReason     string      `json:"trigger_reason,omitempty"`
}

// ActionType is what the orchestrator should do after corroboration.
type ActionType string

const (
	ActionNone         ActionType = "none"
	ActionConfirm      ActionType = "confirm"
	ActionMarkExpired  ActionType = "mark_expired"
	ActionAlertManual  ActionType = "alert_manual"
	ActionTriggerL2    ActionType = "trigger_l2"
	ActionTriggerL4    ActionType = "trigger_l4"
)

// ═══════════════════════════════════════════════════════
// LINK CHECK — enhanced link verification
// ═══════════════════════════════════════════════════════

// LinkResult is the result of checking a bonus link.
type LinkResult struct {
	BonusID      string    `json:"bonus_id"`
	URL          string    `json:"url"`
	StatusCode   int       `json:"status_code"`
	FinalURL     string    `json:"final_url,omitempty"`  // after redirects
	OK           bool      `json:"ok"`
	Redirected   bool      `json:"redirected"`
	Archived     bool      `json:"archived"`             // page moved to archive
	ResponseTime int64     `json:"response_time_ms"`
	CheckedAt    time.Time `json:"checked_at"`
	Error        string    `json:"error,omitempty"`
}

// ═══════════════════════════════════════════════════════
// CIRCUIT BREAKER — for unstable sites
// ═══════════════════════════════════════════════════════

// CircuitState represents the circuit breaker state.
type CircuitState int

const (
	CircuitClosed   CircuitState = iota // Normal: requests flow
	CircuitOpen                        // Tripped: requests blocked
	CircuitHalfOpen                    // Testing: one request allowed
)

func (s CircuitState) String() string {
	switch s {
	case CircuitClosed:
		return "closed"
	case CircuitOpen:
		return "open"
	case CircuitHalfOpen:
		return "half_open"
	default:
		return "unknown"
	}
}

// ═══════════════════════════════════════════════════════
// QUORUM THRESHOLDS
// ═══════════════════════════════════════════════════════

// QuorumConfig holds the thresholds for RSS corroboration.
type QuorumConfig struct {
	Conferma          float64 `json:"conferma"`           // cumulative trust needed to confirm
	Scadenza          float64 `json:"scadenza"`           // cumulative trust needed to mark expired
	ModificaImporto   float64 `json:"modifica_importo"`   // cumulative trust needed for amount change
	MinFontiIndipendenti int  `json:"min_fonti_indipendenti"` // minimum independent sources
}

// DefaultQuorum returns production-safe thresholds.
func DefaultQuorum() QuorumConfig {
	return QuorumConfig{
		Conferma:             2.0,
		Scadenza:             2.5, // higher = more cautious before marking expired
		ModificaImporto:      3.0,
		MinFontiIndipendenti: 2,
	}
}

// ═══════════════════════════════════════════════════════
// PIPELINE STATUS — for admin dashboard
// ═══════════════════════════════════════════════════════

// LevelStatus reports the health of a pipeline level.
type LevelStatus struct {
	Enabled     bool       `json:"enabled"`
	RunCount    int        `json:"run_count"`
	LastRun     *time.Time `json:"last_run,omitempty"`
	LastErr     string     `json:"last_err,omitempty"`
}

// PipelineStatus is the complete pipeline health report.
type PipelineStatus struct {
	Running     bool                    `json:"running"`
	StartedAt   time.Time               `json:"started_at"`
	Levels      map[string]LevelStatus  `json:"levels"`
	EventCount  int                     `json:"event_count"`
	LastEvent   *PipelineEvent          `json:"last_event,omitempty"`
}

// ═══════════════════════════════════════════════════════
// RSS FEED CATEGORIES
// ═══════════════════════════════════════════════════════

// FeedCategory classifies RSS feeds by editorial authority.
type FeedCategory int

const (
	FeedIstituzionale FeedCategory = iota // Institutional sources (trust 1.0)
	FeedAutorevole                        // Authoritative editorial (trust 0.75-0.85)
	FeedEditoriale                        // General editorial (trust 0.50-0.70)
)

// ArticleData is a classified RSS article with extracted metadata.
type ArticleData struct {
	Source      string       `json:"source"`
	Domain      string       `json:"domain"`
	Trust       float64      `json:"trust"`
	Date        time.Time    `json:"date"`
	BonusIDs    []string     `json:"bonus_ids"`
	Importi     []string     `json:"importi,omitempty"`
	SoglieISEE  []float64    `json:"soglie_isee,omitempty"`
	Signal      SignalType   `json:"signal"`
	SignalScore float64      `json:"signal_score"`
	Category    FeedCategory `json:"category"`
}

// ═══════════════════════════════════════════════════════
// GAZZETTA UFFICIALE — L1 events
// ═══════════════════════════════════════════════════════

// GUEventType classifies Gazzetta Ufficiale events.
type GUEventType string

const (
	GUAbrogazione     GUEventType = "abrogazione"
	GUProroga         GUEventType = "proroga"
	GURifinanziamento GUEventType = "rifinanziamento"
	GUConversione     GUEventType = "conversione"
	GUAttuazione      GUEventType = "attuazione"
	GUModifica        GUEventType = "modifica"
	GUNuovo           GUEventType = "nuovo"
)

// GUEvent is an event detected from the Gazzetta Ufficiale.
type GUEvent struct {
	BonusID    string      `json:"bonus_id"`
	Type       GUEventType `json:"type"`
	NormRef    string      `json:"norm_ref"`
	GUTitle    string      `json:"gu_title"`
	GULink     string      `json:"gu_link"`
	GUDate     time.Time   `json:"gu_date"`
	Confidence float64     `json:"confidence"`
}

// ═══════════════════════════════════════════════════════
// NORMATTIVA — L2 legislative text extraction
// ═══════════════════════════════════════════════════════

// NormText holds extracted data from a consolidated legislative text.
type NormText struct {
	NormRef        string            `json:"norm_ref"`
	ImportiTrovati []ImportoNormativo `json:"importi_trovati,omitempty"`
	ISEETrovate    []SogliaISEE      `json:"isee_trovate,omitempty"`
	DateTrovate    []DataNormativa   `json:"date_trovate,omitempty"`
	FetchedAt      time.Time         `json:"fetched_at"`
}

// ImportoNormativo is an amount extracted from legislative text.
type ImportoNormativo struct {
	Valore   string `json:"valore"`
	Contesto string `json:"contesto"`
}

// SogliaISEE is an ISEE threshold extracted from legislative text.
type SogliaISEE struct {
	Valore   float64 `json:"valore"`
	Contesto string  `json:"contesto"`
}

// DataNormativa is a date extracted from legislative text.
type DataNormativa struct {
	Data     time.Time `json:"data"`
	Contesto string    `json:"contesto"`
}

// ═══════════════════════════════════════════════════════
// INSTITUTIONAL SCRAPER — L4 results
// ═══════════════════════════════════════════════════════

// ScrapeResult is the result of scraping an institutional page.
type ScrapeResult struct {
	BonusID   string    `json:"bonus_id"`
	LinkOK    bool      `json:"link_ok"`
	Importo   string    `json:"importo,omitempty"`
	Requisiti string    `json:"requisiti,omitempty"`
	Scadenza  string    `json:"scadenza,omitempty"`
	PageHash  string    `json:"page_hash"`
	FetchedAt time.Time `json:"fetched_at"`
}
