package matcher

import "bonusperme/internal/models"

// GetRegionalBonus returns all regional bonuses for Italian regions.
func GetRegionalBonus() []models.Bonus {
	bonuses := []models.Bonus{
		// ========== PIEMONTE ==========
		{
			ID:          "buono-vesta",
			Nome:        "Buono Vesta",
			Ente:        "Regione Piemonte",
			Categoria:   "famiglia",
			Descrizione: "Contributo per rette nido, sezioni primavera e centri estivi. Fascia: \u20ac1.200 (ISEE<10k), \u20ac1.000 (10k-35k), \u20ac800 (35k-40k). Disabilit\u00e0: \u20ac1.200 se ISEE<40k.",
			Importo:     "\u20ac800-1.200/anno",
			SogliaISEE:  40000,
			Requisiti: []string{
				"Residenza in Piemonte",
				"Figli iscritti a nido/sezioni primavera/centri estivi",
				"ISEE \u2264 \u20ac40.000",
			},
			ComeRichiederlo: []string{
				"Portale Piemonte Tu con SPID/CIE",
				"Domanda nel periodo del bando",
			},
			Documenti: []string{
				"SPID o CIE",
				"ISEE in corso di validit\u00e0",
				"Ricevute rette/iscrizione",
			},
			LinkUfficiale:        "https://www.regione.piemonte.it/web/temi/diritti-politiche-sociali/politiche-sociali/buono-vesta",
			LinkRicerca:          "https://www.google.com/search?q=site:regione.piemonte.it+buono+vesta+nido",
			FonteURL:             "https://www.regione.piemonte.it/web/temi/diritti-politiche-sociali/politiche-sociali/buono-vesta",
			FonteNome:            "Regione Piemonte",
			RiferimentiNormativi: []string{"DGR Piemonte Fondi FSE+ 2021-2027"},
			RegioniApplicabili:   []string{"Piemonte"},
			Scadenza:             "Bando annuale",
			Stato:                "attivo",
			UltimoAggiornamento:  "15 febbraio 2026",
		},
		{
			ID:          "voucher-scuola-piemonte",
			Nome:        "Voucher Scuola Piemonte",
			Ente:        "Regione Piemonte",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri e materiale didattico per studenti di scuola secondaria.",
			Importo:     "fino a \u20ac200",
			SogliaISEE:  20000,
			Requisiti: []string{
				"Residenza in Piemonte",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac20.000",
			},
			ComeRichiederlo: []string{
				"Bando annuale maggio-luglio",
				"Domanda online",
			},
			Documenti: []string{
				"SPID o CIE",
				"ISEE",
				"Iscrizione scolastica",
			},
			LinkUfficiale:       "https://www.regione.piemonte.it/web/temi/istruzione-formazione-lavoro",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.piemonte.it+voucher+scuola",
			FonteURL:            "https://www.regione.piemonte.it/web/temi/istruzione-formazione-lavoro",
			FonteNome:           "Regione Piemonte",
			RegioniApplicabili:  []string{"Piemonte"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== VALLE D'AOSTA ==========
		{
			ID:          "agevolazione-trasporti-vda",
			Nome:        "Agevolazione Trasporto Pubblico VdA",
			Ente:        "Regione Valle d'Aosta",
			Categoria:   "trasporti",
			Descrizione: "Over 65 ISEE<\u20ac20k = gratuito. Studenti universitari: sconto 75-90%. Sconti progressivi per altre fasce.",
			Importo:     "gratuit\u00e0 o sconti 75-90%",
			SogliaISEE:  30000,
			Requisiti: []string{
				"Residenza in Valle d'Aosta",
				"ISEE \u2264 \u20ac30.000",
			},
			ComeRichiederlo: []string{
				"Domanda online o sportelli regionali",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
				"Tessera studente (se applicabile)",
			},
			LinkUfficiale:       "https://www.regione.vda.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.vda.it+agevolazione+trasporto+pubblico",
			FonteURL:            "https://www.regione.vda.it/trasporti",
			FonteNome:           "Regione Valle d'Aosta",
			RegioniApplicabili:  []string{"Valle d'Aosta"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== LOMBARDIA ==========
		{
			ID:          "dote-scuola-lombardia",
			Nome:        "Dote Scuola Materiale Didattico",
			Ente:        "Regione Lombardia",
			Categoria:   "istruzione",
			Descrizione: "Contributo annuale per materiale didattico per studenti di scuola secondaria.",
			Importo:     "fino a \u20ac200/anno",
			SogliaISEE:  15748.78,
			Requisiti: []string{
				"Residenza in Lombardia",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac15.748,78",
			},
			ComeRichiederlo: []string{
				"Piattaforma Bandi Online Regione Lombardia",
			},
			Documenti: []string{
				"SPID o CIE",
				"ISEE",
				"Iscrizione scolastica",
			},
			LinkUfficiale:        "https://www.regione.lombardia.it/wps/portal/istituzionale/HP/istruzione-formazione-lavoro",
			LinkRicerca:          "https://www.google.com/search?q=site:regione.lombardia.it+dote+scuola+materiale+didattico",
			FonteURL:             "https://www.regione.lombardia.it/wps/portal/istituzionale/HP/istruzione-formazione-lavoro",
			FonteNome:            "Regione Lombardia",
			RiferimentiNormativi: []string{"DGR Lombardia annuale"},
			RegioniApplicabili:   []string{"Lombardia"},
			Scadenza:             "Bando annuale",
			Stato:                "attivo",
			UltimoAggiornamento:  "15 febbraio 2026",
		},
		{
			ID:          "misura-unica-affitto-lombardia",
			Nome:        "Misura Unica Affitto Lombardia",
			Ente:        "Regione Lombardia",
			Categoria:   "casa",
			Descrizione: "Contributo per canone di locazione con contratto registrato e incidenza canone >14%.",
			Importo:     "fino a \u20ac3.000/anno",
			SogliaISEE:  26000,
			Requisiti: []string{
				"Residenza in Lombardia",
				"Contratto registrato",
				"ISEE \u2264 \u20ac26.000",
				"Incidenza canone >14%",
			},
			ComeRichiederlo: []string{
				"Bando comunale o regionale annuale",
			},
			Documenti: []string{
				"ISEE",
				"Contratto registrato",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.lombardia.it/wps/portal/istituzionale/HP/casa",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.lombardia.it+misura+unica+affitto",
			FonteURL:            "https://www.regione.lombardia.it/wps/portal/istituzionale/HP/casa",
			FonteNome:           "Regione Lombardia",
			RegioniApplicabili:  []string{"Lombardia"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== TRENTINO-ALTO ADIGE ==========
		{
			ID:          "assegno-unico-trento",
			Nome:        "Assegno Unico Provinciale Trento",
			Ente:        "Provincia Autonoma di Trento",
			Categoria:   "famiglia",
			Descrizione: "Assegno integrativo provinciale per figlio a carico, si aggiunge all'Assegno INPS.",
			Importo:     "fino a \u20ac200/mese per figlio",
			SogliaISEE:  40000,
			Requisiti: []string{
				"Residenza in Provincia di Trento",
				"Figli a carico",
				"ICEF/ISEE \u2264 \u20ac40.000",
			},
			ComeRichiederlo: []string{
				"Agenzia per la Famiglia Trento",
				"Domanda online con SPID",
			},
			Documenti: []string{
				"SPID o CIE",
				"ISEE/ICEF",
				"Codici fiscali figli",
			},
			LinkUfficiale:       "https://www.provincia.tn.it/Servizi/Assegno-unico-provinciale",
			LinkRicerca:         "https://www.google.com/search?q=site:provincia.tn.it+assegno+unico+provinciale",
			FonteURL:            "https://www.provincia.tn.it/Servizi/Assegno-unico-provinciale",
			FonteNome:           "Provincia Autonoma di Trento",
			RegioniApplicabili:  []string{"Trentino-Alto Adige"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
		{
			ID:          "familiengeld-bolzano",
			Nome:        "Familiengeld Bolzano",
			Ente:        "Provincia Autonoma di Bolzano",
			Categoria:   "famiglia",
			Descrizione: "Assegno familiare provinciale per figlio. Usa DURP (dichiarazione unificata).",
			Importo:     "\u20ac100-250/mese per figlio",
			SogliaISEE:  50000,
			Requisiti: []string{
				"Residenza in Provincia di Bolzano",
				"Figli a carico",
				"ISEE \u2264 \u20ac50.000",
			},
			ComeRichiederlo: []string{
				"Ripartizione Famiglia e Welfare Bolzano",
				"Domanda online",
			},
			Documenti: []string{
				"DURP",
				"Documento d'identit\u00e0",
				"Codici fiscali figli",
			},
			LinkUfficiale:       "https://www.provincia.bz.it/famiglia-sociale-comunita/famiglia/default.asp",
			LinkRicerca:         "https://www.google.com/search?q=site:provincia.bz.it+familiengeld+assegno+familiare",
			FonteURL:            "https://www.provincia.bz.it/famiglia-sociale-comunita/famiglia/default.asp",
			FonteNome:           "Provincia Autonoma di Bolzano",
			RegioniApplicabili:  []string{"Trentino-Alto Adige"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== VENETO ==========
		{
			ID:          "bonus-libri-veneto",
			Nome:        "Bonus Libri Scolastici Veneto",
			Ente:        "Regione Veneto",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo. Fascia 1: ISEE \u2264 \u20ac10.632,94. Fascia 2: ISEE \u2264 \u20ac13.500.",
			Importo:     "\u20ac80-200",
			SogliaISEE:  13500,
			Requisiti: []string{
				"Residenza in Veneto",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac13.500",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.veneto.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.veneto.it+bonus+libri+scolastici",
			FonteURL:            "https://www.regione.veneto.it/istruzione",
			FonteNome:           "Regione Veneto",
			RegioniApplicabili:  []string{"Veneto"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== FRIULI VENEZIA GIULIA ==========
		{
			ID:          "carta-famiglia-fvg",
			Nome:        "Carta Famiglia FVG",
			Ente:        "Regione Friuli Venezia Giulia",
			Categoria:   "famiglia",
			Descrizione: "Carta sconti su beni e servizi convenzionati per famiglie con almeno 1 figlio.",
			Importo:     "sconti 5-30% su beni e servizi",
			SogliaISEE:  30000,
			Requisiti: []string{
				"Residenza in FVG",
				"Almeno 1 figlio",
				"ISEE \u2264 \u20ac30.000",
			},
			ComeRichiederlo: []string{
				"Online o uffici comunali",
			},
			Documenti: []string{
				"ISEE",
				"Stato di famiglia",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.fvg.it/rafvg/cms/RAFVG/famiglia-casa/",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.fvg.it+carta+famiglia",
			FonteURL:            "https://www.regione.fvg.it/rafvg/cms/RAFVG/famiglia-casa/",
			FonteNome:           "Regione Friuli Venezia Giulia",
			RegioniApplicabili:  []string{"Friuli Venezia Giulia"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== LIGURIA ==========
		{
			ID:          "trasporto-gratuito-liguria",
			Nome:        "Trasporto Gratuito Under 19 Liguria",
			Ente:        "Regione Liguria",
			Categoria:   "trasporti",
			Descrizione: "Trasporto pubblico gratuito per tutti i residenti under 19. Studenti 19-26: sconto 50%. Nessun requisito ISEE per under 19.",
			Importo:     "gratuito (under 19) / sconto 50% (19-26)",
			SogliaISEE:  0,
			Requisiti: []string{
				"Residenza in Liguria",
				"Under 19 (gratuito) o 19-26 studente (50%)",
			},
			ComeRichiederlo: []string{
				"Richiesta abbonamento presso punti vendita AMT/ATP",
			},
			Documenti: []string{
				"Documento d'identit\u00e0",
				"Certificato residenza",
				"Tessera studente (se 19-26)",
			},
			LinkUfficiale:       "https://www.regione.liguria.it/homepage/trasporti.html",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.liguria.it+trasporto+gratuito+under+19",
			FonteURL:            "https://www.regione.liguria.it/homepage/trasporti.html",
			FonteNome:           "Regione Liguria",
			RegioniApplicabili:  []string{"Liguria"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== EMILIA-ROMAGNA ==========
		{
			ID:          "contributo-nido-emilia",
			Nome:        "Contributo Rette Nido Emilia-Romagna",
			Ente:        "Regione Emilia-Romagna",
			Categoria:   "famiglia",
			Descrizione: "Contributo integrativo al bonus INPS per rette asilo nido.",
			Importo:     "fino a \u20ac600/anno",
			SogliaISEE:  26000,
			Requisiti: []string{
				"Residenza in Emilia-Romagna",
				"Figli iscritti a nido",
				"ISEE \u2264 \u20ac26.000",
			},
			ComeRichiederlo: []string{
				"Portale regionale con SPID",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione nido",
				"Ricevute rette",
			},
			LinkUfficiale:       "https://www.regione.emilia-romagna.it/infanzia",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.emilia-romagna.it+contributo+rette+nido",
			FonteURL:            "https://www.regione.emilia-romagna.it/infanzia",
			FonteNome:           "Regione Emilia-Romagna",
			RegioniApplicabili:  []string{"Emilia-Romagna"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
		{
			ID:          "salta-su-emilia",
			Nome:        "Salta Su \u2014 Trasporto Studenti",
			Ente:        "Regione Emilia-Romagna",
			Categoria:   "trasporti",
			Descrizione: "Trasporto gratuito studenti (bus e treni regionali) per primaria, secondaria e formazione professionale.",
			Importo:     "gratuito",
			SogliaISEE:  30000,
			Requisiti: []string{
				"Residenza in Emilia-Romagna",
				"Iscrizione a scuola/formazione",
				"ISEE \u2264 \u20ac30.000",
			},
			ComeRichiederlo: []string{
				"Portale regionale mobilit\u00e0 con SPID",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://mobilita.regione.emilia-romagna.it/",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.emilia-romagna.it+salta+su+trasporto+studenti",
			FonteURL:            "https://mobilita.regione.emilia-romagna.it/",
			FonteNome:           "Regione Emilia-Romagna",
			RegioniApplicabili:  []string{"Emilia-Romagna"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== TOSCANA ==========
		{
			ID:          "pacchetto-scuola-toscana",
			Nome:        "Pacchetto Scuola Toscana",
			Ente:        "Regione Toscana",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri e materiale in base a livello scolastico. Bando agosto-ottobre.",
			Importo:     "\u20ac130-300",
			SogliaISEE:  36151.98,
			Requisiti: []string{
				"Residenza in Toscana",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac36.151,98",
			},
			ComeRichiederlo: []string{
				"Portale con SPID durante il bando",
			},
			Documenti: []string{
				"SPID",
				"ISEE",
				"Iscrizione scolastica",
			},
			LinkUfficiale:       "https://www.regione.toscana.it/web/guest/istruzione-e-ricerca",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.toscana.it+pacchetto+scuola",
			FonteURL:            "https://www.regione.toscana.it/web/guest/istruzione-e-ricerca",
			FonteNome:           "Regione Toscana",
			RegioniApplicabili:  []string{"Toscana"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== UMBRIA ==========
		{
			ID:          "contributo-libri-umbria",
			Nome:        "Contributo Libri Scolastici Umbria",
			Ente:        "Regione Umbria",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo per studenti di scuola secondaria.",
			Importo:     "fino a \u20ac200",
			SogliaISEE:  15493.71,
			Requisiti: []string{
				"Residenza in Umbria",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac15.493,71",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.umbria.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.umbria.it+contributo+libri+scolastici",
			FonteURL:            "https://www.regione.umbria.it/istruzione",
			FonteNome:           "Regione Umbria",
			RegioniApplicabili:  []string{"Umbria"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== MARCHE ==========
		{
			ID:          "agevolazione-trasporti-marche",
			Nome:        "Agevolazione Trasporto Marche",
			Ente:        "Regione Marche",
			Categoria:   "trasporti",
			Descrizione: "Sconto fino a 70% su abbonamenti per under 26 e over 65. Studenti universitari prioritari.",
			Importo:     "sconto fino a 70%",
			SogliaISEE:  25000,
			Requisiti: []string{
				"Residenza in Marche",
				"Under 26 o Over 65",
				"ISEE \u2264 \u20ac25.000",
			},
			ComeRichiederlo: []string{
				"Domanda online portale regionale",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
				"Tessera studente (se applicabile)",
			},
			LinkUfficiale:       "https://www.regione.marche.it/Regione-Utile/Trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.marche.it+agevolazione+trasporto",
			FonteURL:            "https://www.regione.marche.it/Regione-Utile/Trasporti",
			FonteNome:           "Regione Marche",
			RegioniApplicabili:  []string{"Marche"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== LAZIO ==========
		{
			ID:          "contributo-affitto-lazio",
			Nome:        "Contributo Affitto Lazio",
			Ente:        "Regione Lazio",
			Categoria:   "casa",
			Descrizione: "Contributo per canone di locazione. ISEE \u2264 \u20ac35.000 o reddito \u2264 \u20ac28.770,28. Incidenza canone >24%.",
			Importo:     "fino a \u20ac2.000/anno",
			SogliaISEE:  35000,
			Requisiti: []string{
				"Residenza in Lazio",
				"ISEE \u2264 \u20ac35.000",
				"Incidenza canone >24%",
				"Contratto registrato",
			},
			ComeRichiederlo: []string{
				"Bando comunale annuale",
			},
			Documenti: []string{
				"ISEE",
				"Contratto registrato",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.lazio.it/politiche-abitative",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.lazio.it+contributo+affitto",
			FonteURL:            "https://www.regione.lazio.it/politiche-abitative",
			FonteNome:           "Regione Lazio",
			RegioniApplicabili:  []string{"Lazio"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
		{
			ID:          "bonus-libri-lazio",
			Nome:        "Bonus Libri Lazio",
			Ente:        "Regione Lazio",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo per studenti secondaria I e II grado.",
			Importo:     "variabile per Comune",
			SogliaISEE:  15493.71,
			Requisiti: []string{
				"Residenza in Lazio",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac15.493,71",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.lazio.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.lazio.it+bonus+libri",
			FonteURL:            "https://www.regione.lazio.it/istruzione",
			FonteNome:           "Regione Lazio",
			RegioniApplicabili:  []string{"Lazio"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== ABRUZZO ==========
		{
			ID:          "bonus-libri-abruzzo",
			Nome:        "Bonus Libri Abruzzo",
			Ente:        "Regione Abruzzo",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo per studenti di scuola secondaria.",
			Importo:     "fino a \u20ac200",
			SogliaISEE:  15493.71,
			Requisiti: []string{
				"Residenza in Abruzzo",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac15.493,71",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.abruzzo.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.abruzzo.it+bonus+libri",
			FonteURL:            "https://www.regione.abruzzo.it/istruzione",
			FonteNome:           "Regione Abruzzo",
			RegioniApplicabili:  []string{"Abruzzo"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== MOLISE ==========
		{
			ID:          "contributo-libri-molise",
			Nome:        "Contributo Libri Scolastici Molise",
			Ente:        "Regione Molise",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo per studenti di scuola secondaria.",
			Importo:     "\u20ac80-230",
			SogliaISEE:  15748.78,
			Requisiti: []string{
				"Residenza in Molise",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac15.748,78",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.molise.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.molise.it+contributo+libri+scolastici",
			FonteURL:            "https://www.regione.molise.it/istruzione",
			FonteNome:           "Regione Molise",
			RegioniApplicabili:  []string{"Molise"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== CAMPANIA ==========
		{
			ID:          "trasporti-studenti-campania",
			Nome:        "Trasporti Gratuiti Studenti Campania",
			Ente:        "Regione Campania",
			Categoria:   "trasporti",
			Descrizione: "Trasporto pubblico gratuito per studenti 11-26 anni iscritti a scuola o universit\u00e0.",
			Importo:     "gratuito",
			SogliaISEE:  35000,
			Requisiti: []string{
				"Residenza in Campania",
				"Et\u00e0 11-26 anni",
				"Iscrizione a scuola/universit\u00e0",
				"ISEE < \u20ac35.000",
			},
			ComeRichiederlo: []string{
				"Portale regionale",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica/universitaria",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.campania.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.campania.it+trasporto+gratuito+studenti",
			FonteURL:            "https://www.regione.campania.it/trasporti",
			FonteNome:           "Regione Campania",
			RegioniApplicabili:  []string{"Campania"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
		{
			ID:          "bonus-libri-campania",
			Nome:        "Bonus Libri Campania",
			Ente:        "Regione Campania",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo per studenti di scuola secondaria.",
			Importo:     "fino a \u20ac250",
			SogliaISEE:  13300,
			Requisiti: []string{
				"Residenza in Campania",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac13.300",
			},
			ComeRichiederlo: []string{
				"Domanda al Comune di residenza",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.campania.it/istruzione",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.campania.it+bonus+libri",
			FonteURL:            "https://www.regione.campania.it/istruzione",
			FonteNome:           "Regione Campania",
			RegioniApplicabili:  []string{"Campania"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== PUGLIA ==========
		{
			ID:          "bonus-libri-puglia",
			Nome:        "Bonus Libri Puglia",
			Ente:        "Regione Puglia",
			Categoria:   "istruzione",
			Descrizione: "Contributo per libri di testo. ISEE \u2264 \u20ac11.000 (\u2264 \u20ac14.000 per 3+ figli).",
			Importo:     "fino a \u20ac200",
			SogliaISEE:  11000,
			Requisiti: []string{
				"Residenza in Puglia",
				"Studente scuola secondaria",
				"ISEE \u2264 \u20ac11.000 (\u20ac14.000 per 3+ figli)",
			},
			ComeRichiederlo: []string{
				"Portale StudiInPuglia",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.studiinpuglia.regione.puglia.it",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.puglia.it+bonus+libri",
			FonteURL:            "https://www.studiinpuglia.regione.puglia.it",
			FonteNome:           "Regione Puglia",
			RegioniApplicabili:  []string{"Puglia"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== BASILICATA ==========
		{
			ID:          "agevolazione-trasporti-basilicata",
			Nome:        "Agevolazione Trasporti Basilicata",
			Ente:        "Regione Basilicata",
			Categoria:   "trasporti",
			Descrizione: "Sconto su abbonamenti per studenti, over 65 e disabili. Gratuit\u00e0 per categorie fragili.",
			Importo:     "sconto fino a 50%",
			SogliaISEE:  20000,
			Requisiti: []string{
				"Residenza in Basilicata",
				"Studente, over 65 o disabile",
				"ISEE \u2264 \u20ac20.000",
			},
			ComeRichiederlo: []string{
				"Domanda online portale regionale",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.basilicata.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.basilicata.it+agevolazione+trasporti",
			FonteURL:            "https://www.regione.basilicata.it/trasporti",
			FonteNome:           "Regione Basilicata",
			RegioniApplicabili:  []string{"Basilicata"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== CALABRIA ==========
		{
			ID:          "bonus-trasporti-calabria",
			Nome:        "Bonus Trasporti Studenti Calabria",
			Ente:        "Regione Calabria",
			Categoria:   "trasporti",
			Descrizione: "Sconti abbonamenti per studenti superiori e universitari. Over 65 ISEE <\u20ac20.000: riduzioni significative.",
			Importo:     "sconti abbonamenti",
			SogliaISEE:  30000,
			Requisiti: []string{
				"Residenza in Calabria",
				"Studente superiori/universit\u00e0",
				"ISEE \u2264 \u20ac30.000",
			},
			ComeRichiederlo: []string{
				"Domanda online portale regionale",
			},
			Documenti: []string{
				"ISEE",
				"Iscrizione scolastica/universitaria",
				"Documento d'identit\u00e0",
			},
			LinkUfficiale:       "https://www.regione.calabria.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.calabria.it+bonus+trasporti+studenti",
			FonteURL:            "https://www.regione.calabria.it/trasporti",
			FonteNome:           "Regione Calabria",
			RegioniApplicabili:  []string{"Calabria"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== SICILIA ==========
		{
			ID:          "prima-casa-giovani-sicilia",
			Nome:        "Contributo Prima Casa Giovani Sicilia",
			Ente:        "Regione Siciliana",
			Categoria:   "casa",
			Descrizione: "Contributo a fondo perduto per acquisto prima casa per under 40.",
			Importo:     "fino a \u20ac25.000 a fondo perduto",
			SogliaISEE:  40000,
			Requisiti: []string{
				"Residenza in Sicilia",
				"Under 40",
				"ISEE \u2264 \u20ac40.000",
				"Acquisto prima casa",
			},
			ComeRichiederlo: []string{
				"Bando IRFIS FinSicilia",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
				"Documentazione immobile",
				"Preliminare di acquisto",
			},
			LinkUfficiale:       "https://www.regione.sicilia.it/istituzioni/servizi-informativi/decreti-e-direttive/bando-prima-casa",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.sicilia.it+prima+casa+giovani",
			FonteURL:            "https://www.regione.sicilia.it/istituzioni/servizi-informativi/decreti-e-direttive/bando-prima-casa",
			FonteNome:           "Regione Siciliana",
			RegioniApplicabili:  []string{"Sicilia"},
			Scadenza:            "Bando annuale",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
		{
			ID:          "bonus-trasporti-sicilia",
			Nome:        "Bonus Trasporti Studenti Sicilia",
			Ente:        "Regione Siciliana",
			Categoria:   "trasporti",
			Descrizione: "Sconti su trasporti per studenti. Lavoratori 18-35: sconti 30-40%.",
			Importo:     "sconti su bus/treni/traghetti",
			SogliaISEE:  30000,
			Requisiti: []string{
				"Residenza in Sicilia",
				"Studente o lavoratore 18-35",
				"ISEE \u2264 \u20ac30.000",
			},
			ComeRichiederlo: []string{
				"Richiesta presso aziende trasporto locali",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
				"Iscrizione scolastica o busta paga",
			},
			LinkUfficiale:       "https://www.regione.sicilia.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.sicilia.it+bonus+trasporti+studenti",
			FonteURL:            "https://www.regione.sicilia.it/trasporti",
			FonteNome:           "Regione Siciliana",
			RegioniApplicabili:  []string{"Sicilia"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},

		// ========== SARDEGNA ==========
		{
			ID:          "agevolazione-trasporti-sardegna",
			Nome:        "Agevolazione Trasporti Sardegna",
			Ente:        "Regione Sardegna",
			Categoria:   "trasporti",
			Descrizione: "Sconto 50% su abbonamenti trasporto. Agevolazioni extra per residenti aree interne.",
			Importo:     "sconto 50% abbonamenti",
			SogliaISEE:  25000,
			Requisiti: []string{
				"Residenza in Sardegna",
				"ISEE \u2264 \u20ac25.000",
			},
			ComeRichiederlo: []string{
				"Domanda online o sportelli ARST",
			},
			Documenti: []string{
				"ISEE",
				"Documento d'identit\u00e0",
				"Certificato di residenza",
			},
			LinkUfficiale:       "https://www.regione.sardegna.it/trasporti",
			LinkRicerca:         "https://www.google.com/search?q=site:regione.sardegna.it+agevolazione+trasporti",
			FonteURL:            "https://www.regione.sardegna.it/trasporti",
			FonteNome:           "Regione Sardegna",
			RegioniApplicabili:  []string{"Sardegna"},
			Scadenza:            "In vigore",
			Stato:               "attivo",
			UltimoAggiornamento: "15 febbraio 2026",
		},
	}
	populateValidity(bonuses)
	return bonuses
}
